;--------------------------------------------------
; the following place holders are avaiable
;   %thinbasicinstallpath%    will be replaced with thinBasic installation path
;   %CompilerInstallPath%     will bereplaced with CompilerInstallPath ini configuration
;   %CompilerIncludePath%     will bereplaced with CompilerIncludePath ini configuration
;   %sourcecodefullpathname%  will be replaced with the full path and name of the temp source code
;--------------------------------------------------
